appName: usercode
image:
  registry: docker-hub.middleware.biz
  repository: usercode

alpineImage:
  registry: docker-hub.middleware.biz
  repository: alpine
  tag: 3.18.3

containers:
  prometheusMetricsPort: 9100
