{{- if .Values.global.redis.secret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.redis.secret.name}}
  labels:
    app: {{ .Values.global.product }}
    tier: "redis"
type: Opaque
data:
  {{- range $key, $value := .Values.global.redis.secret.data }}
  {{- if or (hasSuffix "_cache" $key) (hasSuffix "_timers" $key) }}
  {{- $overrideKey := printf "%s.%s" "redis" $key }}
  {{ $key }}: {{ (include $overrideKey $) | b64enc | quote }}
  {{- else }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end}}
