{{- if .Values.global.ingress.tls.enabled }}
{{- if .Values.global.ingress.tls.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.ingress.tls.secret.name | default "tls-ingress-secret" }}
type: Opaque
data:
  {{- $root := . -}}
  {{- range $path, $bytes := .Files.Glob "tls-cert/ingress/ingress-tls.crt" }}
  ingress-tls.crt: '{{ $root.Files.Get $path | b64enc }}'
  {{- end }}
  {{- range $path, $bytes := .Files.Glob "tls-cert/ingress/ingress-tls.key" }}
  ingress-tls.key: '{{ $root.Files.Get $path | b64enc }}'
  {{- end }}
{{- end }}
{{- end }}
