{{- if eq .Values.global.enigma.enabled true }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-config
data:
      production.json: |
        {
            "name": "enigma-key-manager",
            "server": {
            "host": "0.0.0.0",
                "port": 8080
            },
            "logger": {
            "level": "warn",
            "transports": [ "file" ],
            "path": "/ebsmnt/enigma/enigma-key-manager/log",
            "maxSizeInMb": 100,
            "maxFiles": 10
            },
            "storage": {
            "host": "{{ .Values.global.db.secret.data.dbhost }}",
            "port": 5432,
            "database": "enigma",
            "user": "{{ .Values.global.db.secret.data.dbuser }}",
            "password": "{{ .Values.global.db.secret.data.dbpwd }}",
            "ssl": false,
            "min": 2,
            "max": 5,
            "connectionTimeoutMillis": 5000,
            "idleTimeoutMillis": 5000
            },
            "kms": {
                "preferred": "amazon",
                "amazon": {
                    "type": "config-credentials",
                    "config-credentials": {
                        "region": "{{ .Values.global.enigma.key_manager.aws_region }}",
                        "accessKeyId": "{{ .Values.global.enigma.key_manager.accessKeyId }}",
                        "secretAccessKey": "{{ .Values.global.enigma.key_manager.secretAccessKey }}"
                    }
                }  
            }
        }
{{- end }}
