{{- if .Values.global.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.appName }}-root-{{ .Release.Namespace }}
  annotations:
    {{- include "corezoid-root.ingressAnnotations" . | nindent 4 }}
  labels:
    app: {{ .Values.global.product }}
    tier: {{ .Values.appName }}
spec:
  {{- include "ingress.className" . | nindent 2 }}
  rules:
    - host: {{ .Values.global.subdomain}}.{{ .Values.global.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: corezoid-web-adm
                port:
                  number: 80
    - host: {{ .Values.global.web_superadm.subdomain}}.{{ .Values.global.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: corezoid-web-superadm
                port:
                  number: 80
    - host: {{ .Values.global.syncapi.subdomain}}.{{ .Values.global.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: syncapi-main
                port:
                  number: 8090
    {{- if .Values.global.sa.enabled }}
    - host: {{ .Values.global.sa_web.subdomain}}.{{ .Values.global.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: single-account-web
                port:
                  number: 80
    {{- end }}
    {{- if .Values.global.store_dumps.enabled }}
    - host: {{ .Values.global.store_dumps.subdomain }}.{{ .Values.global.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dump-service-node
                port:
                  number: 80
    {{- end }}
  {{- if .Values.global.ingress_tls }}
  tls:
    - hosts:
        {{- if .Values.global.store_dumps.enabled }}
        - {{ .Values.global.store_dumps.subdomain }}.{{ .Values.global.domain }}
        {{- end }}
        - {{ .Values.global.subdomain}}.{{ .Values.global.domain }}
        - {{ .Values.global.web_superadm.subdomain}}.{{ .Values.global.domain }}
        - {{ .Values.global.syncapi.subdomain}}.{{ .Values.global.domain }}
        {{- if .Values.global.sa.enabled }}
        - {{ .Values.global.sa_web.subdomain}}.{{ .Values.global.domain }}
      {{- end }}
      secretName: tls-{{ .Values.appName }}-{{ .Release.Namespace }}
  {{- end }}
{{- end -}}