{{- if .Values.global.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.appName }}-system-{{ .Release.Namespace }}
  annotations:
    {{- include "corezoid-system.ingressAnnotations" . | nindent 4 }}
  labels:
    app: {{ .Values.global.product }}
    tier: {{ .Values.appName }}
spec:
  {{- include "ingress.className" . | nindent 2 }}
  rules:
    - host: {{ .Values.global.subdomain}}.{{ .Values.global.domain }}
      http:
        paths:
          - path: /system
            pathType: Prefix
            backend:
              service:
                name: capi-service-node
                port:
                  number: 9080
  {{- if .Values.global.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.global.subdomain}}.{{ .Values.global.domain }}
      secretName: {{ .Values.global.ingress.tls.SecretName | default "tls-ingress-secret" }}
  {{- end }}
{{- end -}}