{{- if .Values.global.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.appName }}-api-2-{{ .Release.Namespace }}
  annotations:
    {{- include "corezoid-api-2.ingressAnnotations" . | nindent 4 }}
  labels:
    app: {{ .Values.global.product }}
    tier: {{ .Values.appName }}
spec:
  {{- include "ingress.className" . | nindent 2 }}
  rules:
    - host: {{ .Values.global.subdomain}}.{{ .Values.global.domain }}
      http:
        paths:
          - path: /api/2/upload
            pathType: Prefix
            backend:
              service:
                name: corezoid-web-adm
                port:
                  {{- if .Values.global.ingress.tls.enabled }}
                  number: {{ .Values.global.ingress.tls.port | default 8443 }}
                  {{- else }}
                  number: {{ .Values.global.webadm.service_port | default 8080 }}
                  {{- end }}
          - path: /api/2/copy
            pathType: Prefix
            backend:
              service:
                name: corezoid-web-adm
                port:
                  {{- if .Values.global.ingress.tls.enabled }}
                  number: {{ .Values.global.ingress.tls.port | default 8443 }}
                  {{- else }}
                  number: {{ .Values.global.webadm.service_port | default 8080 }}
                  {{- end }}
          - path: /api/2/download
            pathType: Prefix
            backend:
              service:
                name: corezoid-web-adm
                port:
                  {{- if .Values.global.ingress.tls.enabled }}
                  number: {{ .Values.global.ingress.tls.port | default 8443 }}
                  {{- else }}
                  number: {{ .Values.global.webadm.service_port | default 8080 }}
                  {{- end }}
          - path: /api/2/compare
            pathType: Prefix
            backend:
              service:
                name: corezoid-web-adm
                port:
                  {{- if .Values.global.ingress.tls.enabled }}
                  number: {{ .Values.global.ingress.tls.port | default 8443 }}
                  {{- else }}
                  number: {{ .Values.global.webadm.service_port | default 8080 }}
                  {{- end }}
          - path: /api/2/merge
            pathType: Prefix
            backend:
              service:
                name: corezoid-web-adm
                port:
                  {{- if .Values.global.ingress.tls.enabled }}
                  number: {{ .Values.global.ingress.tls.port | default 8443 }}
                  {{- else }}
                  number: {{ .Values.global.webadm.service_port | default 8080 }}
                  {{- end }}
  {{- if .Values.global.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.global.subdomain}}.{{ .Values.global.domain }}
      secretName: {{ .Values.global.ingress.tls.secret.name | default "tls-ingress-secret" }}
  {{- end }}
{{- end -}}