{{- if eq .Values.global.storage "manual" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.appName }}-{{ .Values.global.storage}}-{{ .Release.Name }}
  labels:
    tier: {{ .Values.appName }}
spec:
  storageClassName: {{ .Values.global.storageClassName }}
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /ebsmnt/conf/auth_providers
{{- end }}
