apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.global.product }}
    tier: {{ .Values.appName }}
spec:
  selector:
    app: {{ .Values.global.product }}
    tier: {{ .Values.appName }}
  ports:
  - protocol: TCP
    {{- if .Values.global.ingress.tls.enabled }}
    port: {{ .Values.global.webadm.service_port | default 8443 }}
    targetPort: {{ .Values.global.webadm.service_target_port | default 8443 }}
    {{- else }}
    port: {{ .Values.global.webadm.service_port | default 8080 }}
    targetPort: {{ .Values.global.webadm.service_target_port | default 8080 }}
    {{- end }}
  type: NodePort
